apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
spec:
  containers:
  - image: postgres:10.4
    imagePullPolicy: "IfNotPresent"
    name: postgres-pod
    ports:
     - containerPort: 5432
    envFrom:
     - configMapRef:
         name: postgres-config
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
    volumeMounts:
      - name: postgresdb
        mountPath: /mnt/azure
  volumes:
  - name: postgresdb
    persistentVolumeClaim:
        claimName: azurefile