apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: doctorservice
  name: doctorservice
spec:
  ports:
  - name: "5024"
    port: 5024
    targetPort: 5000
  selector:
    io.kompose.service: doctorservice
status:
  loadBalancer: {}
