apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: loginfunctionality
  name: loginfunctionality
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: loginfunctionality
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: loginfunctionality
    spec:
      imagePullSecrets:
        - name: ibmcloudcred            
      containers:      
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: ' Development'
        - name: RedisCacheConnection
          value: ' rediscache:6379'
        - name: WebApiBaseUrl
          value: ' http://20.185.77.158:5018/api/'
        image: arck8scr.azurecr.io/loginfunctionality:latest
        imagePullPolicy: IfNotPresent             
        name: loginfunctionality
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null      
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: loginfunctionality
  name: loginfunctionality
spec:
  type: NodePort
  ports:
  - name: http
    port: 5014
    targetPort: 80
    protocol: TCP
    nodePort: 30007
  selector:
    io.kompose.service: loginfunctionality
status:
  loadBalancer: {}

