apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: loginfunctionality
  name: loginfunctionality
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: loginfunctionality
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: loginfunctionality
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: ' Development'
        - name: RedisCacheConnection
          value: ' rediscache:6379'
        - name: WebApiBaseUrl
          value: ' http://apigateway:81/api/'
        image: loginfunctionality
        imagePullPolicy: ""
        name: loginfunctionality
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: loginfunctionality
  name: loginfunctionality
spec:
  type: LoadBalancer
  ports:
  - name: "5014"
    port: 5014
    targetPort: 80
  selector:
    io.kompose.service: loginfunctionality
status:
  loadBalancer: {}

