apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: loginfunctionality
  name: loginfunctionality
spec:
  ports:
  - name: "5014"
    port: 5014
    targetPort: 80
  selector:
    io.kompose.service: loginfunctionality
status:
  loadBalancer: {}
