apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: patientservice
  name: patientservice
spec:
  ports:
  - name: "5022"
    port: 5022
    targetPort: 81
  selector:
    io.kompose.service: patientservice
status:
  loadBalancer: {}
