apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: postgresdata
  name: postgresdata
spec:
  type: LoadBalancer
  ports:
  - name: "51036"
    port: 51036
    targetPort: 5432
  selector:
    io.kompose.service: postgresdata
status:
  loadBalancer: {}
