apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: postgresqldapper
  name: postgresqldapper
spec:
  ports:
  - name: "5010"
    port: 5010
    targetPort: 5001
  selector:
    io.kompose.service: postgresqldapper
status:
  loadBalancer: {}
