apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: productservice
  name: productservice
spec:
  ports:
  - name: "5020"
    port: 5020
    targetPort: 80
  selector:
    io.kompose.service: productservice
status:
  loadBalancer: {}
